<!-- en la cabecera del HTML -->
<meta charset="UTF-8">

<?php echo $this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
?>

<!-- Le styles -->
<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon02.ico'))
                ->prependStylesheet($this->basePath('css/main.css'))
                ->prependStylesheet($this->basePath('css/foundation.min.css')) ?>

<!-- Scripts -->
<?php echo $this->headScript()
    ->prependFile($this->basePath('js/portada.js'))
    ->prependFile($this->basePath('js/foundation/foundation.orbit.js'))
    ->prependFile($this->basePath('js/vendor/modernizr.js'))
    ->prependFile($this->basePath('js/foundation.min.js'))
    ->prependFile($this->basePath('js/vendor/jquery.js'))
; ?>
