<!-- Reveal Modals begin -->
<div id="firstModal" class="reveal-modal" data-reveal aria-labelledby="firstModalTitle" aria-hidden="true" role="dialog">
	<h2 id="firstModalTitle">Detalle.</h2>
	<img src="img/real/img01.jpg" alt="Facultad de Arquitectura y Ciencias del Hábitat" />
	<p>La Carrera de Turismo, permite que el futuro profesional pueda desempeñarse en cualquier realidad o contexto en el que exista dinámica turística, porque los aprendizajes adquiridos son de índole global.</p>
	
	<p>
		<a href="#" data-reveal-id="secondModal" class="secondary button">Siguiente...</a>
	</p>
	<a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>

<div id="secondModal" class="reveal-modal" data-reveal aria-labelledby="firstModalTitle" aria-hidden="true" role="dialog">
	<h2 id="firstModalTitle">Detalle.</h2>
	<img src="img/real/img02.jpg" alt="Facultad de Arquitectura y Ciencias del Hábitat" />
	<p>La Carrera de Turismo, permite que el futuro profesional pueda desempeñarse en cualquier realidad o contexto en el que exista dinámica turística, porque los aprendizajes adquiridos son de índole global.</p>
	
	<p>
		<a href="#" data-reveal-id="tercerModal" class="secondary button">Siguiente...</a>
	</p>
	<a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>

<div id="tercerModal" class="reveal-modal" data-reveal aria-labelledby="firstModalTitle" aria-hidden="true" role="dialog">
	<h2 id="firstModalTitle">Detalle.</h2>
	<img src="img/real/img03.jpg" alt="Facultad de Arquitectura y Ciencias del Hábitat" />
	<p>La Carrera de Turismo, permite que el futuro profesional pueda desempeñarse en cualquier realidad o contexto en el que exista dinámica turística, porque los aprendizajes adquiridos son de índole global.</p>
	
	<p>
		<a href="#" data-reveal-id="cuartoModal" class="secondary button">Siguiente...</a>
	</p>
	<a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>

<div id="cuartoModal" class="reveal-modal" data-reveal aria-labelledby="secondModalTitle" aria-hidden="true" role="dialog">
	<h2 id="secondModalTitle">This is a second modal.</h2>
	<img src="img/real/img04.jpg" alt="Facultad de Arquitectura y Ciencias del Hábitat" />
	<p>
		See? It just slides into place after the other first modal. Very handy when you need subsequent dialogs, or when a modal option impacts or requires another decision.
	</p>
	<a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>

<!-- Reveal Modals end -->


