<!-- Top menu bar -->
<nav class="tab-bar">
	<section class="left-small">
		<a class="left-off-canvas-toggle menu-icon" href="#"><span></span></a>
	</section>
	<section class="middle tab-bar-section">
		<h1 class="title">Atractivo Turístico</h1>
	</section>
	<section class="right-small">
		<a class="right-off-canvas-toggle menu-icon" href="#"><span></span></a>
	</section>
</nav>

<!-- Left menu -->
<aside class="left-off-canvas-menu">
	<ul class="off-canvas-list">
		<li><label>Pages</label></li>
		<li><a href="index.php">Home</a></li>
		<li><a href="#">DESCRIPCIÓN DEL ATRACTIVO</a></li>
		<li><a href="#">ACTIVIDADES TURÍSTICAS</a></li>
		<li><a href="#">ATRACTIVOS SIMILARES</a></li>
		<li><a href="#">GALERÍA DE FOTOS</a></li>
		<li><a href="#">GEOREFERENCIACIÓN</a></li>
		<li><a href="#">ARCHIVOS ADJUNTOS</a></li>
		<li><a href="#">QUÉ ENCONTRAMOS?</a></li>
	</ul>
</aside>

<!-- Right menu -->
<aside class="right-off-canvas-menu">
	<ul class="off-canvas-list">
		<li><label>Enlaces</label></li>
		<li><a href="basic.php">Atractivos</a></li>
		<li><a href="#">Servicios</a></li>
		<li><a href="public.php">Publicaciones</a></li>
		<li class="has-submenu">
			<a href="public.php"><label>Publicaciones</label></a>
			<ul class="right-submenu">
				<li class="back">
					<a href="#">Volver</a>
				</li>
				<li><label>Publicaciones</label></li>
				<li><a href="public_list.php">Patrimonio</a></li>
				<li><a href="public_list-1.php">Productos y destinos turísticos</a></li>
				<li class="has-submenu">
					<a href="public_list-2.php">Actores y emprendimientos turísticos</a>
					<ul class="right-submenu">
						<li class="back"><a href="#">Volver</a></li>
						<li><label>Actores y emprendimientos turísticos</label></li>
						<li><a href="#">emprendimiento-01</a></li>
						<li><a href="#">emprendimiento-02</a></li>
						<li><a href="#">actor-01</a></li>
					</ul>
				</li>
			</ul>
		</li>
		<li><a href="#">Apoyo docente-estudiantil</a></li>
		<li><a href="#">Contáctanos</a></li>
		<li><a href="#">FAQ</a></li>
	</ul>
</aside>

