<!-- El pie de mi página :) -->

<div class="row bg-20 hulk-2">
	<div class="medium-12 columns centrar tc-1">
		
		<!-- varias rows -->
		<!-- 1er fila -->
		<div class="row">
			<div class="medium-12 columns">
				 La Carrera de Turismo perteneciente a la Facultad de Arquitectura y Ciencias del Hábitat de la Universidad Mayor de San Simón - Telf: 4540438 - Email: turismo@arq.umss.edu.bo
			</div>
		</div>

		<!-- segunda fila -->
		<div class="row umss">
			<div class="medium-12 columns">
				<small>Cochabamba - Bolivia</small>
			</div>											
		</div>

		<!-- 3ra fila -->
		<div class="row bonito">
			<div class="medium-12 columns">
				<small>"Inventing tomorrow's solutions around the world"</small>
			</div>
		</div>

	</div>
</div>
