<div class="small-6 columns">
	<div class="row bg-22 bordecito-2">
		<div class="medium-12 columns">
			<strong>JERARQUÍA:</strong>
		</div>
	</div>
	<div class="row">
		<div class="medium-12 columns bg-23 bordecito-2">
			II
		</div>
	</div>
</div>

<div class="small-6 columns">
	<div class="row bg-22 bordecito-2">
		<div class="medium-12 columns">
			<strong>CÓDIGO:</strong>
		</div>
	</div>
	<div class="row">
		<div class="medium-12 columns bg-23 bordecito-2">
			02.05.02
		</div>
	</div>
</div>
</div>
<br />					
<div class="row">
<div class="medium-12 columns">
	<!-- Triggers the modals -->
	<p class="centrar">
		<a href="#" data-reveal-id="firstModal" class="">
			<img id="img_central" src="<?php echo $this->basePath('img/atractivo.jpg') ?>" alt="Facultad de Arquitectura y Ciencias del Hábitat" />
		</a>
	</p>
</div>


