<ul class="accordion centrar" data-accordion>

	<li class="accordion-navigation">
		<a href="#panel4a"><small class="">ESTACIONALIDAD</small></a>
		<div id="panel4a" class="content active borde">
			<div class="row bg-15">
				<div class="medium-12 columns">
					<strong>Meses de visita</strong>
				</div>
			</div>
			<div class="row">
				<div class="medium-12 columns">
					Abril - Noviembre
				</div>
			</div>
			<div class="row bg-15">
				<div class="medium-12 columns">
					<strong>Horas de visita</strong>
				</div>
			</div>
			<div class="row">
				<div class="medium-12 columns">
					08:00 - 12:00
				</div>
			</div>
		</div>
	</li>
	<li class="accordion-navigation">
		<a href="#panel3a"><small class="">OTROS DATOS</small></a>
		<div id="panel3a" class="content borde">
			<div class="row bg-15">
				<div class="medium-12 columns">
					<strong>Altitud</strong>
				</div>
			</div>
			<div class="row">
				<div class="medium-12 columns">
					2800 m.s.n.m.
				</div>
			</div>
			<div class="row bg-15">
				<div class="medium-12 columns">
					<strong>Clima</strong>
				</div>
			</div>
			<div class="row">
				<div class="medium-12 columns">
					Frío
				</div>
			</div>
			<div class="row bg-15">
				<div class="medium-12 columns">
					<strong>Derecho de uso</strong>
				</div>
			</div>
			<div class="row">
				<div class="medium-12 columns">
					Público
				</div>
			</div>
		</div>
	</li>
</ul>
<!-- se termina el acordeón -->

