<header class="contain-to-grid sticky">
	<nav class="top-bar" data-topbar role="navigation">
		<ul class="title-area">
			<li class="name"><h1><a href="index.php">Atractivos turísticos</a></h1></li>
			<li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
		</ul>
		 
		<section class="top-bar-section">
			<ul class="left">
				<li class="active"><a href="basic.php">Atractivos</a></li>
				<li><a href="#">Servicios</a></li>
				<li class="has-dropdown">
					<a href="public.php">Publicaciones</a>
					<ul class="dropdown">
						<li><a href="public_list.php">Patrimonio</a></li>
						<li><a href="public_list-1.php">Productos y destinos turísticos</a></li>
						<li class="has-dropdown"><a href="public_list-2.php">Actores y emprendimientos turísticos</a>
							<ul class="dropdown">
								<li><a href="#">emprendimiento-01</a></li>
								<li><a href="#">emprendimiento-02</a></li>
								<li><a href="#">actor-01</a></li>
							</ul>
						</li>
					</ul>
					
				</li>
				<li><a href="#">Apoyo docente-estudiantil</a><li>
			</ul>
			 
			<ul class="right">
				<li><a href="#">Contáctanos</a></li>
				<li><a href="#">FAQ</a></li>
			</ul>
		</section>
	</nav>
</header>

