<?php echo $this->doctype(); ?>

<html lang="es_ES">
    <head>
        <?php echo $this->headMeta()->setCharset('utf8') ?>
        <?php echo $this->headTitle($this->title) ?>
       
        <?php echo $this->headLink()->prependStylesheet($this->basePath().'/css/estilos.css') ?>
        <?php echo $this->headStyle() ?>
        <?php echo $this->headScript()->prependFile($this->basePath().'/js/jquery.min.js') ?>
    </head>
    <body>
		<div id="header">Encabeza, No jeta larga, no duro el corazón</div>

		<div class="content">
			<h1>Saludo : <?php echo $this->saludo ?> </h1>

			<?php echo $this->content?>
		</div>


        <div class="footer">footer</div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>


