<div class="off-canvas-wrap" data-offcanvas>
	<div class="inner-wrap">

		<!-- APROBADO -->
		<?php echo $this->navegacionat ?>
		
		<!-- Main content -->
		<section class="main-section">
			<div class="row">
				<div class="small-12 columns">
					<!-- los indicadores -->
					<div class="row">

						<div class="medium-12 columns">

							<!-- APROBADO -->
							<?php echo $this->cejat ?>
		
						</div>

					</div>

					<!-- cuando me muestres contenido -->

					<div class="row">			
						<div class="medium-12 columns bg-15">
							<div class="row">

								<div class="medium-9 columns bg-21">

									<!-- APROBADO -->
									<?php echo $this->ventanat ?>

								</div>
								<div class="medium-3 columns">

									<?php echo $this->puertat ?>

								</div>

							</div>

						</div>
					</div>

					<!--
					dl = definition list
					dt = definition term
					dd = definition data
					-->

					<!-- Just like you -->

					<!-- APROBADO mevoy -->
					<?php echo $this->mevoy ?>

				</div>
			</div>

			<!-- APROBADO pie -->
			<?php echo $this->pie ?>

		</section>

		<!-- Exit overlay -->
		<a class="exit-off-canvas"></a>

	</div>
</div>

