<?php
// module/Atractivo/view/atractivo/atractivo/edit.phtml:

$title = 'Edit atractivo';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
	'atractivo',
	array(
		'action' => 'edit',
		'id' => $this->cod_at,
	)
));
$form->prepare();

echo $this->form()->openTag($form);

echo $this->formHidden($form->get('cod_at'));

echo $this->formRow($form->get('nombre_at'));
echo $this->formRow($form->get('descripcion'));
echo $this->formRow($form->get('fotos'));
echo $this->formRow($form->get('coordenadas'));
echo $this->formRow($form->get('direc_foto'));

echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();






