<!-- Factorar código -->

<?php 
	function estilo()
	{
?>

		<!-- en la cabecera del HTML -->
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />

		<link rel="shortcut icon" href="img/favicon02.ico">
		<link rel="stylesheet" href="css/foundation.min.css">
		<!-- <link rel="stylesheet" href="css/foundation.css"> -->
		<link rel="stylesheet" href="css/main.css">

		<script src="js/vendor/modernizr.js"></script>

		<script src="js/vendor/jquery.js"></script>
		<script src="js/foundation.min.js"></script>
		<script src="js/foundation/foundation.orbit.js"></script>
		<script src="js/portada.js"></script>

<?php
	}
	
	function logotipo()
	{
?>
		<div class="row bg-12 hulk">
						
			<div class="medium-2 columns">
			
				<div class="row">
				
					<div class="medium-9 medium-offset-3 columns">
						<img src="img/LOGO_TURISMO.png" alt="Facultad de Arquitectura y Ciencias del Hábitat" />
					</div>
					
				</div>
				
			</div>
			<div class="medium-10 columns">
				
				<div class="row">
					<div class="medium-8 columns">
						<h6 class="subheader tc-1">
							Facultad de Arquitectura y Ciencias del Hábitat
						</h6>
					</div>
					<div class="medium-2 medium-offset-2 columns">
						<a href="#" class="cabezota tc-1">
							Iniciar<br />sesión
						</a>
					</div>
				</div>
				<div class="row">
					<div class="medium-12 columns">
						<h1 class="cabezota tc-1">CARRERA DE TURISMO</h1>
					</div>

				</div>
				
			</div>
						
		</div>
<?php
	}

	function orbit()
	{
?>
		<div class="row hulk-1">
			
			<div class="medium-12 columns">
				<ul class="example-orbit" data-orbit>
					<li>
						<img src="img/orbit01.jpg" alt="slide 1" />
						<div class="orbit-caption">
							<blockquote class="tc-1">
								Aventura.
								<cite class="tc-1">Miguel Guzman</cite>
							</blockquote>
						</div>
					</li>
					<li class="active">
						<img src="img/orbit02.jpg" alt="slide 2" />
						<div class="orbit-caption">
							<blockquote class="tc-1">
								Canotaje y navegación.
								<cite class="tc-1">Miguel Guzman</cite>
							</blockquote>
						</div>
					</li>
					<li>
						<img src="img/orbit03.jpg" alt="slide 3" />
						<div class="orbit-caption">
							<blockquote class="tc-1">
								Guiadas.
								<cite class="tc-1">Miguel Guzman</cite>
							</blockquote>
						</div>
					</li>
					<li>
						<img src="img/orbit04.jpg" alt="slide 4" />
						<div class="orbit-caption">
							<blockquote class="tc-1">
								Tracking de caminata.
								<cite class="tc-1">Miguel Guzman</cite>
							</blockquote>
						</div>
					</li>
				</ul>
			</div>

		</div>

<?php
	}
	
	function dondeEstoy()
	{
?>
		<div class="row">

			<div class="medium-12 columns">

				<ul class="breadcrumbs">
					<li>
						<a href="#"><span class="success label">Clasificación</span></a>
					</li>
					<li><a href="#">Patrimonio Histórico</a></li>
					<li><a href="#">Paleontología</a></li>
					<li class="current"><a href="#">Yacimientos fosiliferos</a></li>
				</ul>
				
				<!-- Basic -->
				<div data-alert class="alert-box radius">
					¡Bienvenidos!...
					<a href="#" class="close">&times;</a>
				</div>

			</div>

		</div>

<?php
	}

	function piePage()
	{
?>
		<div class="row bg-20 hulk-2">
			<div class="medium-12 columns centrar tc-1">
				
				<!-- varias rows -->
				<!-- 1er fila -->
				<div class="row">
					<div class="medium-12 columns">
						 La Carrera de Turismo perteneciente a la Facultad de Arquitectura y Ciencias del Hábitat de la Universidad Mayor de San Simón - Telf: 4540438 - Email: turismo@arq.umss.edu.bo
					</div>
				</div>

				<!-- segunda fila -->
				<div class="row umss">
					<div class="medium-12 columns">
						<small>Cochabamba - Bolivia</small>
					</div>											
				</div>

				<!-- 3ra fila -->
				<div class="row bonito">
					<div class="medium-12 columns">
						<small>"Inventing tomorrow's solutions around the world"</small>
					</div>
				</div>

			</div>
		</div>

<?php
	}
	
	function elMenu()
	{
?>
		<nav class="top-bar umss" data-topbar role="navigation">

			<!-- Logo -->
			<ul class="title-area">
				<li class="name">
					<h1>
						<a href="#">
							<strong class="tc-4 bonito01">Atractivos turísticos de Cochabamba</strong>
						</a>
					</h1>
				</li>
				<li class="toggle-topbar menu-icon">
					<a href="#"><span></span></a>
				</li>
			</ul>
			
			<!-- Buttons -->
			<section class="top-bar-section">

				<!-- Right buttons -->
				<ul class="right">
					<li class="divider"></li>
					<li class="has-dropdown">
						<a href="public.php">Publicaciones</a>
						<ul class="dropdown">
							<li><a href="public_list.php">Patrimonio</a></li>
							<li><a href="public_list-1.php">Productos y destinos turísticos</a></li>
							<li class="has-dropdown"><a href="public_list-2.php">Actores y emprendimientos turísticos</a>
								<ul class="dropdown">
									<li><a href="#">emprendimiento-01</a></li>
									<li><a href="#">emprendimiento-02</a></li>
									<li><a href="#">actor-01</a></li>
								</ul>
							</li>
						</ul>
					</li>
					<li class="divider"></li>
					<li class="has-dropdown">
						<a href="#">Apoyo docente-estudiantil</a>
						<ul class="dropdown">
							<li><a href="#">Moodle</a></li>
							<li><a href="#">Facebook</a></li>
							<li><a href="#">Tesis</a></li>
						</ul>
					</li>
				</ul>
				
				<!-- Left buttons -->
				<ul class="left">
					<li class="divider"></li>
					<li>
						<a href="basic.php">
							<span class="bonito">Atractivos</span>
						</a>
					</li>
					<li class="divider"></li>
					<li>
						<a href="#">
							<span class="bonito">Servicios</span>
						</a>
					</li>
					<li class="divider"></li>

					<!-- Search -->
					<li class="has-form">
						<div class="row collapse">
							<div class="medium-8 columns">
								<input type="text" placeholder="Encuentra tu atractivo turístico...">
							</div>
							<div class="medium-4 columns">
								<a href="#" class="small button success radius">Buscar</a>
							</div>
						</div>
					</li>
				</ul>

			</section>

		</nav>

<?php
	}

	function menuOption()
	{
?>
		<header class="contain-to-grid sticky">
			<nav class="top-bar" data-topbar role="navigation">
				<ul class="title-area">
					<li class="name"><h1><a href="index.php">Atractivos turísticos</a></h1></li>
					<li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
				</ul>
				 
				<section class="top-bar-section">
					<ul class="left">
						<li class="active"><a href="basic.php">Atractivos</a></li>
						<li><a href="#">Servicios</a></li>
						<li class="has-dropdown">
							<a href="public.php">Publicaciones</a>
							<ul class="dropdown">
								<li><a href="public_list.php">Patrimonio</a></li>
								<li><a href="public_list-1.php">Productos y destinos turísticos</a></li>
								<li class="has-dropdown"><a href="public_list-2.php">Actores y emprendimientos turísticos</a>
									<ul class="dropdown">
										<li><a href="#">emprendimiento-01</a></li>
										<li><a href="#">emprendimiento-02</a></li>
										<li><a href="#">actor-01</a></li>
									</ul>
								</li>
							</ul>
							
						</li>
						<li><a href="#">Apoyo docente-estudiantil</a><li>
					</ul>
					 
					<ul class="right">
						<li><a href="#">Contáctanos</a></li>
						<li><a href="#">FAQ</a></li>
					</ul>
				</section>
			</nav>
		</header>
<?php		
	}
	
	function menuVertical()
	{
?>
		<ul class="tabs vertical centrar" data-tab>
		
			<li class="tab-title active borde">
				<a href="#panel11"><span class="bonito01">DESCRIPCIÓN DEL ATRACTIVO</span></a>
			</li>
			
			<li class="tab-title borde">
				<a href="#panel21"><span class="bonito01">ACTIVIDADES TURÍSTICAS</span></a>
			</li>
			
			<li class="tab-title borde">
				<a href="#panel21"><span class="bonito01">ATRACTIVOS SIMILARES</span></a>
			</li>
			
			<li class="tab-title borde">
				<a href="#panel41"><span class="bonito01">GALERÍA DE FOTOS</span></a>
			</li>
			
			<li class="tab-title borde">
				<a href="#panel51"><span class="bonito01">GEOREFERENCIACIÓN</span></a>
			</li>
			
			<li class="tab-title borde">
				<a href="#panel31"><span class="bonito01">ARCHIVOS ADJUNTOS</span></a>
			</li>
			<li class="">
				
			</li>
		
		</ul>

<?php
	}

	function contenidoVertical()
	{
?>
		<div class="tabs-content vertical">
		
			<div class="content active" id="panel11">
				<div class="row">
					<div class="medium-12 columns">
						

						
					</div>
				</div>
					
				<h5>Descripción del atractivo:</h5>
				<div class="panel callout radius">
					<p>El Parque Metropolitano se encuentra ubicado al noroeste de la ciudad de Sacaba, dentro de la zona de Arocagua y abarca un área de 78.413 hectáreas.</p>
					<p>Esta área protegida es muy afectada por la realización de actividades agrícolas, la extracción de áridos, el vertido de desechos sólidos, la contaminación de los cursos de agua, la contaminación acústica, asentamientos ilegales, entre otras, que naturalmente también tienen impacto en la biodiversidad presente en la zona.</p>
					<p>"En las evaluaciones de campo se tuvo oportunidad de registrar, a través de los cantos que producen, dos especies de anfibios (...). Las especies fueron registradas en inmediaciones de cuerpos de agua en la zona evaluada", dice el informe de la Gobernación.</p>
					<p>"El Parque Metropolitano es un área que alberga una riqueza importante de especies (...), por lo que se recomienda su protección y conservación", añade y concluye que la Gobernación debe impulsar la realización de mayores estudios de investigación de diversidad en el Parque Metropolitano.</p>
				</div>
										
			</div>
			<div class="content" id="panel21">
				<p>This is the second panel of the basic tab example. This is the second panel of the basic tab example.</p>
			</div>
			<div class="content" id="panel31">
				<p>This is the third panel of the basic tab example. This is the third panel of the basic tab example.</p>
			</div>
			<div class="content" id="panel41">
				<p>This is the fourth panel of the basic tab example. This is the fourth panel of the basic tab example.</p>
			</div>
		
		</div>

<?php
	}

	function detallando()
	{
?>
		<!-- Just like you -->

		<!-- Reveal Modals begin -->
		<div id="firstModal" class="reveal-modal" data-reveal aria-labelledby="firstModalTitle" aria-hidden="true" role="dialog">
			<h2 id="firstModalTitle">Detalle.</h2>
			<img src="img/real/img01.jpg" alt="Facultad de Arquitectura y Ciencias del Hábitat" />
			<p>La Carrera de Turismo, permite que el futuro profesional pueda desempeñarse en cualquier realidad o contexto en el que exista dinámica turística, porque los aprendizajes adquiridos son de índole global.</p>
			
			<p>
				<a href="#" data-reveal-id="secondModal" class="secondary button">Siguiente...</a>
			</p>
			<a class="close-reveal-modal" aria-label="Close">&#215;</a>
		</div>

		<div id="secondModal" class="reveal-modal" data-reveal aria-labelledby="firstModalTitle" aria-hidden="true" role="dialog">
			<h2 id="firstModalTitle">Detalle.</h2>
			<img src="img/real/img02.jpg" alt="Facultad de Arquitectura y Ciencias del Hábitat" />
			<p>La Carrera de Turismo, permite que el futuro profesional pueda desempeñarse en cualquier realidad o contexto en el que exista dinámica turística, porque los aprendizajes adquiridos son de índole global.</p>
			
			<p>
				<a href="#" data-reveal-id="tercerModal" class="secondary button">Siguiente...</a>
			</p>
			<a class="close-reveal-modal" aria-label="Close">&#215;</a>
		</div>

		<div id="tercerModal" class="reveal-modal" data-reveal aria-labelledby="firstModalTitle" aria-hidden="true" role="dialog">
			<h2 id="firstModalTitle">Detalle.</h2>
			<img src="img/real/img03.jpg" alt="Facultad de Arquitectura y Ciencias del Hábitat" />
			<p>La Carrera de Turismo, permite que el futuro profesional pueda desempeñarse en cualquier realidad o contexto en el que exista dinámica turística, porque los aprendizajes adquiridos son de índole global.</p>
			
			<p>
				<a href="#" data-reveal-id="cuartoModal" class="secondary button">Siguiente...</a>
			</p>
			<a class="close-reveal-modal" aria-label="Close">&#215;</a>
		</div>

		<div id="cuartoModal" class="reveal-modal" data-reveal aria-labelledby="secondModalTitle" aria-hidden="true" role="dialog">
			<h2 id="secondModalTitle">This is a second modal.</h2>
			<img src="img/real/img04.jpg" alt="Facultad de Arquitectura y Ciencias del Hábitat" />
			<p>
				See? It just slides into place after the other first modal. Very handy when you need subsequent dialogs, or when a modal option impacts or requires another decision.
			</p>
			<a class="close-reveal-modal" aria-label="Close">&#215;</a>
		</div>

		<!-- Reveal Modals end -->
<?php
	}
	
	function acordeon()
	{
?>
<!-- If you are using version 5.5 or greater you can use <ul>'s and <li>'s for Accordion markup --> 

		<ul class="accordion centrar" data-accordion>
			<li class="accordion-navigation">
				<a href="#panel1a" class=""><small class="">COORDENADAS UTM</small></a>
				<div id="panel1a" class="content active borde">
					<div class="row bg-15">
						<div class="medium-12 columns">
							<strong>Longitud</strong>
						</div>
					</div>
					<div class="row">
						<div class="medium-12 columns">
							799960
						</div>
					</div>
					<div class="row bg-15">
						<div class="medium-12 columns">
							<strong>Latitud</strong>
						</div>
					</div>
					<div class="row">
						<div class="medium-12 columns">
							8092415
						</div>
					</div>
				</div>
			</li>

			<li class="accordion-navigation">
				<a href="#panel2a"><small class="">REFERENCIAS DE LOCALIZACIÓN</small></a>

				<div id="panel2a" class="content borde">
					<div class="row bg-15">
						<div class="medium-12 columns">
							<strong>DEPARTAMENTO</strong>
						</div>
					</div>
					<div class="row">
						<div class="medium-12 columns">
							Potosí
						</div>
					</div>
					<div class="row bg-15">
						<div class="medium-12 columns">
							<strong>PROVINCIA</strong>
						</div>
					</div>
					<div class="row">
						<div class="medium-12 columns">
							Gral. B. Bilbao Rioja
						</div>
					</div>
					<div class="row bg-15">
						<div class="medium-12 columns">
							<strong>MUNICIPIO</strong>
						</div>
					</div>
					<div class="row">
						<div class="medium-12 columns">
							Acasio
						</div>
					</div>
					<div class="row bg-15">
						<div class="medium-12 columns">
							<strong>SITIO O LUGAR</strong>
						</div>
					</div>
					<div class="row">
						<div class="medium-12 columns">
							Yanayo
						</div>
					</div>
				</div>
			</li>
			<li class="accordion-navigation">
				<a href="#panel4a"><small class="">ESTACIONALIDAD</small></a>
				<div id="panel4a" class="content borde">
					<div class="row bg-15">
						<div class="medium-12 columns">
							<strong>Meses de visita</strong>
						</div>
					</div>
					<div class="row">
						<div class="medium-12 columns">
							Abril - Noviembre
						</div>
					</div>
					<div class="row bg-15">
						<div class="medium-12 columns">
							<strong>Horas de visita</strong>
						</div>
					</div>
					<div class="row">
						<div class="medium-12 columns">
							08:00 - 12:00
						</div>
					</div>
				</div>
			</li>
			<li class="accordion-navigation">
				<a href="#panel3a"><small class="">OTROS DATOS</small></a>
				<div id="panel3a" class="content borde">
					<div class="row bg-15">
						<div class="medium-12 columns">
							<strong>Altitud</strong>
						</div>
					</div>
					<div class="row">
						<div class="medium-12 columns">
							2800 m.s.n.m.
						</div>
					</div>
					<div class="row bg-15">
						<div class="medium-12 columns">
							<strong>Clima</strong>
						</div>
					</div>
					<div class="row">
						<div class="medium-12 columns">
							Frío
						</div>
					</div>
					<div class="row bg-15">
						<div class="medium-12 columns">
							<strong>Derecho de uso</strong>
						</div>
					</div>
					<div class="row">
						<div class="medium-12 columns">
							Público
						</div>
					</div>
				</div>
			</li>
		</ul>
		<!-- se termina el acordeón -->

<?php
	}

	function tablita()
	{
?>
		<div class="medium-3 columns centrar">

			<div class="row bg-15">
				<div class="medium-12 columns borde">
					<strong>JERARQUÍA:</strong>
				</div>
			</div>
			<div class="row">
				<div class="medium-12 columns">
					II
				</div>
			</div>
			<div class="row bg-15">
				<div class="medium-12 columns borde">
					<strong>CÓDIGO:</strong>
				</div>
			</div>
			<div class="row">
				<div class="medium-12 columns">
					02.05.02
				</div>
			</div>
	
			<!--<br />-->
			<br />
			<br />
	
		</div>

<?php
	}

	function tituloEImagen()
	{
?>
		<div class="row">
			<div class="medium-9 columns">
				<h5 class="subheader">En el municipio de Toro Toro</h5>
				<h2>Huellas de Dinosaurio</h2>

				<!-- Triggers the modals -->
				<p class="centrar">
					<a href="#" data-reveal-id="firstModal" class="">
						<img id="img_central" src="img/atractivo.jpg" alt="Facultad de Arquitectura y Ciencias del Hábitat" />
					</a>
				</p>
			</div>
		
		</div>
<?php
	}
?>
